<?php

return [

    'niche_detector' => [
        'threshold' => 0.15,
        'keywords' => [
            'sensual', 'hot', 'sexy', 'onlyfans', 'privacy', 'conteúdo adulto',
            'conteudo adulto', '+18', 'nsfw', 'pack', 'fetiche', 'erótico', 'erotico',
            'sedução', 'seducao', 'lingerie', 'boudoir', 'spicy', 'sem filtro',
        ],
    ],

    'neighborhoods' => [
        [
            'id' => 'premium',
            'name' => 'Bairro Premium',
            'tag' => 'Elite',
            'emoji' => '🏆',
            'score_min' => 85,
            'score_max' => 100,
            'prompt_style' => 'mansão contemporânea, paisagismo impecável, piscina, vidro, madeira e alto padrão',
        ],
        [
            'id' => 'influenciadores',
            'name' => 'Torre dos Influenciadores',
            'tag' => 'Top Creators',
            'emoji' => '🏢',
            'score_min' => 78,
            'score_max' => 94,
            'prompt_style' => 'edifício alto padrão, cobertura exclusiva, vista urbana, estética de creator premium',
        ],
        [
            'id' => 'experts',
            'name' => 'Alameda dos Experts',
            'tag' => 'Especialistas',
            'emoji' => '💼',
            'score_min' => 65,
            'score_max' => 87,
            'prompt_style' => 'arquitetura moderna, minimalista, tecnológica, luzes discretas, vidro, concreto, home office sofisticado',
        ],
        [
            'id' => 'fitness',
            'name' => 'Vila do Fitness',
            'tag' => 'Saúde',
            'emoji' => '💪',
            'score_min' => 60,
            'score_max' => 84,
            'prompt_style' => 'casa clara, ativa, área externa, academia sutil, clima saudável',
        ],
        [
            'id' => 'resenha',
            'name' => 'Vila da Resenha',
            'tag' => 'Humor',
            'emoji' => '😂',
            'score_min' => 55,
            'score_max' => 81,
            'prompt_style' => 'casa social, divertida, acolhedora, varanda, luz quente, clima de vizinhança movimentada',
        ],
        [
            'id' => 'conversa',
            'name' => 'Praça da Conversa',
            'tag' => 'Debates',
            'emoji' => '💬',
            'score_min' => 50,
            'score_max' => 77,
            'prompt_style' => 'casa com varanda ampla, ambiente acolhedor para conversas, iluminação convidativa',
        ],
        [
            'id' => 'iniciantes',
            'name' => 'Pracinha dos Iniciantes',
            'tag' => 'Novatos',
            'emoji' => '🌱',
            'score_min' => 30,
            'score_max' => 54,
            'prompt_style' => 'casa modesta mas charmosa, jardim simples, clima de começo de jornada',
        ],
        [
            'id' => 'silencio',
            'name' => 'Subúrbio do Silêncio',
            'tag' => 'Observadores',
            'emoji' => '🔇',
            'score_min' => 20,
            'score_max' => 47,
            'prompt_style' => 'casa simples, discreta, aconchegante, reservada, iluminação suave',
        ],
        [
            'id' => 'treta',
            'name' => 'Delegacia da Treta',
            'tag' => 'Polêmicos',
            'emoji' => '🚨',
            'score_min' => 40,
            'score_max' => 69,
            'prompt_style' => 'estética urbana, dramática, contrastes fortes, mas sem violência explícita',
        ],
        [
            'id' => 'esquecido',
            'name' => 'Bairro Esquecido',
            'tag' => 'Inativos',
            'emoji' => '👻',
            'score_min' => 5,
            'score_max' => 24,
            'prompt_style' => 'casa simples, discreta, um pouco esquecida, vegetação crescendo, clima nostálgico',
            'inactive' => true,
        ],
        [
            'id' => 'cemiterio',
            'name' => 'Cemitério das Contas',
            'tag' => 'R.I.P.',
            'emoji' => '⚰️',
            'score_min' => 0,
            'score_max' => 4,
            'prompt_style' => 'casa abandonada, atmosfera melancólica, sem destruição explícita',
            'disconnected' => true,
        ],
        [
            'id' => 'sem_filtro',
            'name' => 'Bairro Sem Filtro',
            'tag' => 'Sem Filtro',
            'emoji' => '🔥',
            'score_min' => null,
            'score_max' => null,
            'prompt_style' => 'casa noturna, iluminação quente e discreta, estética sofisticada e sugestiva, sem conteúdo explícito',
            'niche' => 'adult',
        ],
        [
            'id' => 'lancadores',
            'name' => 'Jardim dos Lançadores',
            'tag' => 'Marketing',
            'emoji' => '🚀',
            'score_min' => 70,
            'score_max' => 89,
            'prompt_style' => 'casa moderna, comercial, vitrine, energia de negócios e marketing',
        ],
    ],

];
